### ISSUE TITLE
[Bug] 启动 BetterGI 时出错 PaddleOcr 预热失败

### ISSUE THREAD

**Issue by Mcayear** [babalae/better-genshin-impact#132]
![image](https://github.com/babalae/better-genshin-impact/assets/48203962/7f12b7fd-8bbf-4ad1-8020-b3db99147d62)

设备信息：

[![piyhby6.png](https://z1.ax1x.com/2023/12/04/piyhby6.png)](https://imgse.com/i/piyhby6)
[![piyhHQx.png](https://z1.ax1x.com/2023/12/04/piyhHQx.png)](https://imgse.com/i/piyhHQx)
[![piyh7S1.png](https://z1.ax1x.com/2023/12/04/piyh7S1.png)](https://imgse.com/i/piyh7S1)

**Comment by emako** [comment]
onnxruntime.dll依赖MSVCP140.DLL

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by huiyadanli** [comment]
据说中文路径也会造成这个问题。

有人把文件放在了桌面会出现这个报错，移动路径后解决。

但是我没有复现。

**Comment by emako** [comment]
没事加个中文路径警告 @huiyadanli

**Comment by huiyadanli** [comment]
![JW}BQBLHTIS~T6(_HSA@{%0_tmb](https://github.com/babalae/better-genshin-impact/assets/15783049/c7adb3d2-9e3e-4f8f-9907-9b98b62e83cd)

有通过系统编码成功解决这个问题的用户。

**Comment by huiyadanli** [comment]
补充

Win11SD：
主页：https://developer.microsoft.com/ja-jp/windows/downloads/windows-sdk/
安装包：https://go.microsoft.com/fwlink/?linkid=2250105

**Comment by huiyadanli** [comment]
> onnxruntime.dll依赖MSVCP140.DLL（侦测：[paddle2onnx.csv](https://github.com/babalae/better-genshin-impact/files/13542766/paddle2onnx.csv)）
> 
> 安装包URL：https://aka.ms/vs/17/release/vc_redist.x64.exe

![KRO0}0EVI TN@WF 6VFJD20](https://github.com/babalae/better-genshin-impact/assets/15783049/ae9cca97-9502-4bbb-ad29-153ebe355e1b)

onnxruntime.dll 加载失败（为FAIL的情况）使用此方案可以解决

![image](https://github.com/babalae/better-genshin-impact/assets/15783049/b5a8496c-4dfc-49ea-91f3-d0beea9a6578)

**Comment by ooaaeiei** [comment]
![50CZ9DSLDB4}Z}MYJ7E10BR](https://github.com/babalae/better-genshin-impact/assets/154801903/bb805c14-5af6-4014-9611-2311a172de9f)

**Comment by huiyadanli** [comment]
已经很久没有新增情况了。Issue先关了。

所有解决方案都整理到文档中了：https://bgi.huiyadan.com/faq.html#%E2%9D%93%E6%8F%90%E7%A4%BA-paddleocr%E9%A2%84%E7%83%AD%E5%A4%B1%E8%B4%A5-%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

**Comment by modan1998** [comment]
![Image](https://github.com/user-attachments/assets/9ce4d1a8-2031-479b-b749-1e458e930c3a)这是什么情况啊

**Comment by Ssmakewe** [comment]
![Image](https://github.com/user-attachments/assets/c9bf3f68-01fc-4843-8eb8-d9b41c896451)这是什么情况，我把解决方法上的5种都试了，还是不行，还有什么地方出现问题吗？

**Comment by qasdasd1020** [comment]
之前用的好好的，5.8的更新之后就有了问题

<img width="545" height="451" alt="Image" src="https://github.com/user-attachments/assets/49886366-9a86-40ba-a2ac-5c6999e6309d" />

报错问题这里详细
更好的原神 v0.48.0.0
2025/8/17 0:25:17 Windows 10.0.19045.2
```
System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
 ---> System.BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)
   at BetterGenshinImpact.ViewModel.MainWindowViewModel.<OcrPreheating>b__22_0() in D:\a\better-genshin-impact\better-genshin-impact\BetterGenshinImpact\ViewModel\MainWindowViewModel.cs:line 299
   at BetterGenshinImpact.ViewModel.MainWindowViewModel.OcrPreheating() in D:\a\better-genshin-impact\better-genshin-impact\BetterGenshinImpact\ViewModel\MainWindowViewModel.cs:line 277
   --- End of inner exception stack trace ---
   at OpenCvSharp.Internal.NativeMethods.imgcodecs_imdecode_vector(Byte* buf, Int32 bufLength, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Cv2.ImDecode(ReadOnlySpan`1 span, ImreadModes flags)
   at OpenCvSharp.Cv2.ImDecode(Byte[] buf, ImreadModes flags)
   at OpenCvSharp.Mat.ImDecode(Byte[] imageBytes, ImreadModes mode)
   at OpenCvSharp.Mat.FromImageData(Byte[] imageBytes, ImreadModes mode)
   at OpenCvSharp.Mat.FromStream(Stream stream, ImreadModes mode)
   at BetterGenshinImpact.GameTask.GameTaskManager.LoadAssetImage(String featName, String assertName, ISystemInfo systemInfo, ImreadModes flags) in D:\a\better-genshin-impact\better-genshin-impact\BetterGenshinImpact\GameTask\GameTaskManager.cs:line 174
   at BetterGenshinImpact.GameTask.GameTaskManager.LoadAssetImage(String featName, String assertName, ImreadModes flags) in D:\a\better-genshin-impact\better-genshin-impact\BetterGenshinImpact\GameTask\GameTaskManager.cs:line 150
   at BetterGenshinImpact.GameTask.GameLoading.Assets.GameLoadingAssets..ctor() in D:\a\better-genshin-impact\better-genshin-impact\BetterGenshinImpact\GameTask\GameLoading\Assets\GameLoadingAssets.cs:line 15
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by huiyadanli** [comment]
@qasdasd1020 重新安装软件。应该是自动更新把有些文件更新坏了
