### ISSUE TITLE
[bug] 七圣召唤开始后立即出错

### ISSUE THREAD

**Issue by TiSpH** [babalae/better-genshin-impact#238]
- 系统环境 / System Environment：
Windows 11 23H2
1920*1080分辨率

- BetterGI版本号 / BetterGI Version：
0.23.0

- 问题描述 / Description of the issue：

<img width="304" alt="Screenshot 2024-01-23 at 8 26 43 PM" src="https://github.com/babalae/better-genshin-impact/assets/14122965/0310ae03-6b4d-4c99-ac4a-06c231a56e50">

- 复现步骤 / Reproduction steps：
<img width="142" alt="Screenshot 2024-01-23 at 8 33 23 PM" src="https://github.com/babalae/better-genshin-impact/assets/14122965/29ca262c-c750-4619-9ac1-6a678ddebdd3">

<img width="462" alt="Screenshot 2024-01-23 at 8 33 55 PM" src="https://github.com/babalae/better-genshin-impact/assets/14122965/e6733213-ced2-439f-b51a-49013a288a95">

选择8号牌组，游戏中也选择雷神柯莱刻晴并开始任意对局
```
[20:20:35.632] [ERR] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows

[20:20:35.632] [DBG] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
   at GeniusInvokationAutoToy.Utils.Retry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 maxAttemptCount) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\Utils\Retry.cs:line 56
   at GeniusInvokationAutoToy.Utils.Retry.Do(Action action, TimeSpan retryInterval, Int32 maxAttemptCount) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\Utils\Retry.cs:line 25
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.GeniusInvokationControl.CommonDuelPrepare() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\GeniusInvokationControl.cs:line 185
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel.Run(GeniusInvokationTaskParam taskParam) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\Model\Duel.cs:line 75
```

**Comment by TiSpH** [comment]
原因出在选择牌组后不会立即生效，需要重启BetterGI。问题已关闭
