### ISSUE TITLE
全自动七星召唤启动报错

### ISSUE THREAD

**Issue by kotonamihuiren** [babalae/better-genshin-impact#64]
选择手牌内个界面点击启动然后报错 Cannot marshal: Encountered unmappable character
管理员权限已开 分辨率1920x1080 16:9

![image](https://github.com/babalae/better-genshin-impact/assets/56951494/ad440728-0cb2-40c8-93cf-92c39c753320)

**Comment by huiyadanli** [comment]
`User\AutoGeniusInvokation` 下的七圣召唤策略不存在？

**Comment by kotonamihuiren** [comment]
这个是要编写策略吗

**Comment by kotonamihuiren** [comment]
是有的 莫纳砂糖琴 我的卡组也是这套

**Comment by kotonamihuiren** [comment]
用了作者的老版本可以正常运行 betterGI报错

**Comment by huiyadanli** [comment]
这个报错是策略解析失败，没修改过策略吧

**Comment by kotonamihuiren** [comment]
没有动任何地方 默认配置运行

**Comment by nyano** [comment]
![image](https://github.com/babalae/better-genshin-impact/assets/5079651/0ae00ce0-a3b1-42cc-9e9d-fc47a62da615)
4k DPI 150%

**Comment by huiyadanli** [comment]
@nyano 看上去是截屏失败了，试试其他功能能否正常运作

**Comment by Mr-Quin** [comment]
@huiyadanli 
我也碰到了这个问题，是OpenCV在读取非unicode文件名时会出现的问题。我用的英文Windows11
https://github.com/opencv/opencv/issues/4292

错误信息
···
[00:48:04.296] [INF] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
→ "全自动七圣召唤，启动！"

[00:48:04.309] [ERR] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
Cannot marshal: Encountered unmappable character.

[00:48:04.501] [ERR] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
   at System.Runtime.InteropServices.Marshal.StringToAnsiString(String s, Byte* buffer, Int32 bufferLength, Boolean bestFit, Boolean throwOnUnmappableChar)
   at System.StubHelpers.CSTRMarshaler.ConvertToNative(Int32 flags, String strManaged, IntPtr pNativeBuffer)
   at OpenCvSharp.Internal.NativeMethods.imgcodecs_imread_Windows(String fileName, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Internal.NativeMethods.imgcodecs_imread(String fileName, Int32 flags, IntPtr& returnValue)
   at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
   at BetterGenshinImpact.GameTask.GameTaskManager.LoadAssetImage(String featName, String assertName, ImreadModes flags) in C:\Code\better-genshin-impact\BetterGenshinImpact\GameTask\GameTaskManager.cs:line 94
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.Assets.AutoGeniusInvokationAssets..ctor() in C:\Code\better-genshin-impact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\Assets\AutoGeniusInvokationAssets.cs:line 38
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.GeniusInvokationControl..ctor() in C:\Code\better-genshin-impact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\GeniusInvokationControl.cs:line 69
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.GeniusInvokationControl.GetInstance() in C:\Code\better-genshin-impact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\GeniusInvokationControl.cs:line 57
   at BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel.Run(GeniusInvokationTaskParam taskParam) in C:\Code\better-genshin-impact\BetterGenshinImpact\GameTask\AutoGeniusInvokation\Model\Duel.cs:line 70

[00:48:04.503] [INF] BetterGenshinImpact.GameTask.AutoGeniusInvokation.Model.Duel
← "退出全自动七圣召唤"
···

**Comment by huiyadanli** [comment]
[0.17.0](https://github.com/babalae/better-genshin-impact/releases/tag/0.17.0) 已经修复这个问题
