### ISSUE TITLE
[bug] 使用 全自动 里的功能会出现报错

### ISSUE THREAD

**Issue by hlzhushiyang** [babalae/better-genshin-impact#656]
无法使用地图坐标相关的功能，点击运行自动晶蝶脚本

- 系统环境 / System Environment：
win11 23h2 专业版

- BetterGI版本号 / BetterGI Version：
0.34.4

- 问题描述 / Description of the issue：

脚本铵了m地图键之后，重复点击枫丹。
在调度器内右键 添加追踪任务， 会出现报错System.IO.DirectoryNotFoundException
更好的原神 v0.34.4.0
2024/9/20 23:48:08 Windows 10.0.22631.2
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\BetterGI\BetterGI\User\AutoPathing'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at BetterGenshinImpact.ViewModel.Pages.ScriptControlViewModel.LoadAllPathingScripts() in c:\projects\better-genshin-impact\BetterGenshinImpact\ViewModel\Pages\ScriptControlViewModel.cs:line 246
   at BetterGenshinImpact.ViewModel.Pages.ScriptControlViewModel.OnAddPathing() in c:\projects\better-genshin-impact\BetterGenshinImpact\ViewModel\Pages\ScriptControlViewModel.cs:line 167
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

- 复现步骤 / Reproduction steps：

1.点击自动运行脚本
2.等待脚本执行，出现重复点击枫丹的情况

或者
1.在调度器内右键，点击添加 路径追踪任务
2.出现问题描述中的报错

**Comment by huiyadanli** [comment]
最新编译版本无地图特征数据

**Comment by huiyadanli** [comment]
需要手动从release中的其他版本获取 `Assets/Map` 下的所有文件
