### ISSUE TITLE
[bug] F9开启自动秘境时，按F11会程序退出

### ISSUE THREAD

**Issue by ZedeX** [babalae/better-genshin-impact#669]
- 系统环境 / System Environment：
Microsoft Windows [版本 10.0.19045.4894] x64

- BetterGI版本号 / BetterGI Version：
0.34.1

- 问题描述 / Description of the issue：
F9开启自动秘境时，按F11会程序退出

- 复现步骤 / Reproduction steps：
按F11启动程序后，按F9启动自动秘境，再按F11，100%复现。上一版本无此问题。

相关log：

[08:04:47.092] [DBG] BetterGenshinImpact.View.MainWindow
主窗体实例化

[08:07:29.440] [INF] BetterGenshinImpact.View.MaskWindow
更好的原神 "0.34.1"

[08:07:29.441] [INF] BetterGenshinImpact.View.MaskWindow
遮罩窗口已启动，游戏大小1920x1080，素材缩放"1.00"，DPI缩放1.5

[08:07:30.801] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
战斗脚本解析完成，共27条指令，涉及角色："钟离,行秋,夜兰,芙宁娜,珐露珊,云堇,班尼特,流浪者"

[08:07:30.802] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
→ "自动秘境，启动！" 用尽所有体力后结束

[08:07:31.160] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
强制指定队伍角色:"流浪者,钟离,雷电将军,夜兰"

[08:07:32.707] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
截图失败!

[08:07:32.924] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
尝试多次后,截图失败!

[08:07:32.942] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
   at BetterGenshinImpact.GameTask.Common.TaskControl.CaptureGameBitmap(IGameCapture gameCapture) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\Common\TaskControl.cs:line 134
   at BetterGenshinImpact.GameTask.TaskTriggerDispatcher.CaptureToRectArea(Boolean forceNew) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\TaskTriggerDispatcher.cs:line 521
   at BetterGenshinImpact.GameTask.Common.TaskControl.CaptureToRectArea(Boolean forceNew) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\Common\TaskControl.cs:line 184
   at BetterGenshinImpact.GameTask.AutoDomain.AutoDomainTask.EnterDomain() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoDomain\AutoDomainTask.cs:line 212
   at BetterGenshinImpact.GameTask.AutoDomain.AutoDomainTask.Start() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoDomain\AutoDomainTask.cs:line 79

[08:07:32.942] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
截图失败!

[08:07:33.130] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
→ "自动秘境结束"

（然后按F11进程就挂了，没有log输出）

**Comment by huiyadanli** [comment]
F11无法终止独立任务 https://github.com/babalae/better-genshin-impact/issues/388

已经改造完毕了，下版本就好了

**Comment by huiyadanli** [comment]
https://github.com/babalae/better-genshin-impact/releases/tag/0.35
