### ISSUE TITLE
[bug] 使用自动追踪采集素材时大地图无法识别并传送

### ISSUE THREAD

**Issue by Skinyi** [babalae/better-genshin-impact#728]
- 系统环境 / System Environment：
Windows11 24h2

- BetterGI版本号 / BetterGI Version：
0.35

- 问题描述 / Description of the issue：
**使用自动追踪采集素材，自动传送打开大地图时无法进行传送，相关日志内容：**
[18:03:23.540] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
("4322.2","1172.8") 最近的传送点位置 ("4325.0","1172.1")
[18:03:24.649] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
离目标传送点最近的区域是："须弥"
[18:03:25.583] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
切换到区域："须弥"
[18:03:28.232] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
传送失败，重试 1 次
BetterGenshinImpact.GameTask.AutoGeniusInvokation.Exception.RetryException: 当前不在地图界面
   at BetterGenshinImpact.GameTask.Common.NewRetry.Do[T](Func`1 action, TimeSpan retryInterval, Int32 maxAttemptCount) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\Common\NewRetry.cs:line 46
   at BetterGenshinImpact.GameTask.Common.NewRetry.Do(Action action, TimeSpan retryInterval, Int32 maxAttemptCount) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\Common\NewRetry.cs:line 16
   at BetterGenshinImpact.GameTask.AutoTrackPath.TpTask.GetBigMapRect() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoTrackPath\TpTask.cs:line 279
   at BetterGenshinImpact.GameTask.AutoTrackPath.TpTask.TpOnce(Double tpX, Double tpY, Boolean force) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoTrackPath\TpTask.cs:line 65
   at BetterGenshinImpact.GameTask.AutoTrackPath.TpTask.Tp(Double tpX, Double tpY, Boolean force) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoTrackPath\TpTask.cs:line 158

- 复现步骤 / Reproduction steps：
1. 地图追踪->脚本仓库->订阅所需脚本，2. 调度器->新增配置组->添加路径追踪任务，3. 调度器->运行配置组

**Comment by huiyadanli** [comment]
你确定你的基础功能比如说自动拾取是能够正常使用的吗？

**Comment by Skinyi** [comment]
无法使用，更新后第一时间试的调度器，没有自动拾取过材料。

**Comment by Skinyi** [comment]
> 你确定你的基础功能比如说自动拾取是能够正常使用的吗？

无法使用，更新后第一时间试的调度器，没有自动拾取过材料。

**Comment by huiyadanli** [comment]
https://bgi.huiyadan.com/quickstart.html 请重新阅读快速上手

大概率是系统更新导致 BitBlt 截图方式的失效，参考 https://github.com/babalae/better-genshin-impact/issues/92
