### ISSUE TITLE
[bug] BetterGI再次调用出现报错

### ISSUE THREAD

**Issue by WQ568** [babalae/better-genshin-impact#781]
- 系统环境 / System Environment：Windows11

- BetterGI版本号 / BetterGI Version：0.36.1

- 问题描述 / Description of the issue：BetterGL初次使用后关闭其图像识别功能，且程序在后台运行，一天后再次使按F11快捷键调用其图像识别，程序出现报错窗口，具体如下图：

- 复现步骤 / Reproduction steps：
- 
![Image](https://github.com/user-attachments/assets/4dac29b2-d6d4-40b6-94c0-cf822d364db4)

更好的原神 v0.36.1.0
2024/11/11 19:35:43 Windows 10.0.22631.2
```
System.InvalidOperationException: 关闭窗口后，无法设置可见性，也无法调用 Show、ShowDialogor 或 WindowInteropHelper.EnsureHandle。
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.Start(IntPtr hWnd) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 211
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.OnStartTriggerAsync() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 197
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by huiyadanli** [comment]
这个报错是因为遮罩窗口销毁后无法重新打开。请确认是否稳定复现该问题

**Comment by WQ568** [comment]
请问应该如何确认是否稳定复现？
