### ISSUE TITLE
自动录制启动出现问题

### ISSUE THREAD

**Issue by lsp0086** [babalae/better-genshin-impact#826]
- 系统环境 / System Environment：
win11 22h2
战神z8d6 4060 i712650h

- BetterGI版本号 / BetterGI Version：
0.37.1

- 问题描述 / Description of the issue：
按照你们说的用bitbit无法截取到原神国际服图像
![Image](https://github.com/user-attachments/assets/fb2df0d4-1c05-4a4e-a079-150d4cd37f7d)
换为第三个可以截图，我以为可以用了
![Image](https://github.com/user-attachments/assets/34a796f5-2210-40be-a4cd-90c4223989d6)
结果运行脚本录制出现以下报错
更好的原神 v0.37.1.0
2024/11/30 星期六 11:03:54 Windows 10.0.22621.2
```
SharpDX.SharpDXException: HRESULT: [0x80004005], Module: [General], ApiCode: [E_FAIL/Unspecified error], Message: 未指定的错误

   at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.DInput.DirectInput8Create(IntPtr hinst, Int32 dwVersion, Guid riidltf, IntPtr& vOutOut, ComObject unkOuterRef)
   at SharpDX.DirectInput.DirectInput..ctor()
   at BetterGenshinImpact.Core.Monitor.DirectInputMonitor..ctor() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Core\Monitor\DirectInputMonitor.cs:line 17
   at BetterGenshinImpact.Core.Recorder.GlobalKeyMouseRecord.StartRecord() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Core\Recorder\GlobalKeyMouseRecord.cs:line 71
   at BetterGenshinImpact.ViewModel.Pages.KeyMouseRecordPageViewModel.OnStartRecord() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\KeyMouseRecordPageViewModel.cs:line 96
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
按理说我的系统环境肯定是齐全的毕竟搞过编程

- 复现步骤 / Reproduction steps：

上述所说

**Comment by huiyadanli** [comment]
dxinput 监听启动失败，和截图方式无关，和你本机的DirectX有关

还有 Win10 BitBlt 基本都能够正常使用，无法使用的找系统问题

**Comment by lsp0086** [comment]
> DirectX

我是win11 大哥
directx有问题是指的要重装吗

**Comment by huiyadanli** [comment]
Win11 的话，你现在就可以重试 BitBlt 了，程序会自动关闭窗口优化，让 BitBlt 变得可用。https://github.com/babalae/better-genshin-impact/issues/92

DirectX 问题你自行研究，现在这个问题你是第一个反馈的，无多个复现样例的情况下，我无法解答。
