### ISSUE TITLE
[bug]截图器启动报错

### ISSUE THREAD

**Issue by Jianxin3** [babalae/better-genshin-impact#850]
- 系统环境 / System Environment：
- windows 10 22H2
- Nvidia GTX950
- 显卡驱动版本：362.00

- BetterGI版本号 / BetterGI Version：
- 0.37.1

- 问题描述 / Description of the issue：
截图器启动失败，报错Unspecified Error

- 复现步骤 / Reproduction steps：开启原神后点击启动截图器

更好的原神 v0.37.1.0
12/11/2024 12:20:35 AM Windows 10.0.19045.2
```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(576)\onnxruntime.dll!00007FFD062863E3: (caller: 00007FFD062079D9) Exception(2) tid(2240) 80004005 Unspecified error

   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(Byte[] modelData, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(Byte[] model, SessionOptions options)
   at Compunet.YoloV8.YoloV8Predictor..ctor(BinarySelector model, YoloV8Metadata metadata, YoloV8Configuration configuration, SessionOptions options)
   at Compunet.YoloV8.YoloV8Builder.Build()
   at BetterGenshinImpact.GameTask.AutoFishing.AutoFishingTrigger..ctor() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\AutoFishing\AutoFishingTrigger.cs:line 35
   at BetterGenshinImpact.GameTask.GameTaskManager.LoadInitialTriggers() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\GameTaskManager.cs:line 45
   at BetterGenshinImpact.GameTask.TaskTriggerDispatcher.Start(IntPtr hWnd, CaptureModes mode, Int32 interval) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\GameTask\TaskTriggerDispatcher.cs:line 140
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.Start(IntPtr hWnd) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 205
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.OnStartTriggerAsync() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 197
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Jianxin3** [comment]
显卡驱动更新到版本466.22，问题解决

**Comment by huiyadanli** [comment]
onnxruntime 无法正常初始化，软件启动后（未开启截图器）时候是否会弹出错误？

**Comment by Jianxin3** [comment]
没有

**Comment by Jianxin3** [comment]
> onnxruntime 无法正常初始化，软件启动后（未开启截图器）时候是否会弹出错误？

没有

**Comment by huiyadanli** [comment]
> 显卡驱动更新到版本466.22，问题解决

原来已经解决，那这个issue先关了
