### ISSUE TITLE
[bug]请补充标题内容

### ISSUE THREAD

**Issue by naclhhn** [babalae/better-genshin-impact#854]
- 系统环境 / System Environment：
- win11

- BetterGI版本号 / BetterGI Version：
0.37.1

- 问题描述 / Description of the issue：
- 更好的原神 v0.37.1.0
2024/12/12 11:50:44 Windows 10.0.26120.2
```
System.InvalidOperationException: 关闭窗口后，无法设置可见性，也无法调用 Show、ShowDialogor 或 WindowInteropHelper.EnsureHandle。
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.Start(IntPtr hWnd) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 211
   at BetterGenshinImpact.ViewModel.Pages.HomePageViewModel.OnStartTriggerAsync() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\ViewModel\Pages\HomePageViewModel.cs:line 197
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

- 复现步骤 / Reproduction steps：
- 不确定

**Comment by huiyadanli** [comment]
是否长时间在停止状态下，挂机了bgi程序，然后再启动？

这个问题应该重启整个软件后就好了
