### ISSUE TITLE
[bug] 安柏的头像识别失败

### ISSUE THREAD

**Issue by a08381** [babalae/better-genshin-impact#869]
- 系统环境 / System Environment：Windows11

- BetterGI版本号 / BetterGI Version：0.37.1

- 问题描述 / Description of the issue：在队伍识别的过程中识别安柏的头像失败

- 复现步骤 / Reproduction steps：

队伍中编入钟离，小鹿，早柚和安柏

- 出错日志：

```
[11:11:48.669] [DBG] BetterGenshinImpact.View.MainWindow
主窗体实例化

[11:12:05.208] [INF] BetterGenshinImpact.View.MaskWindow
更好的原神 "0.37.1"

[11:12:05.211] [INF] BetterGenshinImpact.View.MaskWindow
遮罩窗口已启动，游戏大小1920x1080，素材缩放"1.00"，DPI缩放1

[11:12:19.114] [INF] BetterGenshinImpact.Service.ScriptService
配置组 "圣遗物" 包含实时任务操作调用

[11:12:19.114] [INF] BetterGenshinImpact.Service.ScriptService
配置组 "圣遗物" 加载完成，共5个脚本，开始执行

[11:12:19.116] [INF] BetterGenshinImpact.GameTask.TaskRunner
→ "任务启动！"

[11:12:19.399] [INF] BetterGenshinImpact.Service.ScriptService
------------------------------

[11:12:19.400] [INF] BetterGenshinImpact.Service.ScriptService
→ 开始执行JS脚本: "狗粮ABE路线，自动拾取分解"

[11:12:19.764] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
path: A; swapPath: false; extra: true; autoSalvage: true; autoSalvage4: false; autoSalvageSpan: 10;

[11:12:19.802] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
("253.1","1285.1") 最近的传送点位置 ("253.4","1285.8")

[11:12:21.937] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
识别当前大地图位置："(x:4498.3955 y:3630.8447)"

[11:12:21.937] [DBG] BetterGenshinImpact.GameTask.Common.TaskControl
离目标传送点最近的区域是："蒙德"

[11:12:22.993] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
切换到区域："蒙德"

[11:12:23.845] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
传送点不在当前大地图范围内，继续移动

[11:12:29.372] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
点击传送点

[11:12:38.787] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
传送完成

[11:12:47.799] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
开始执行A线路。

[11:13:02.821] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-璃月-珉林-北-5个.json

[11:13:03.542] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.49940336，结果：AmborCostumeWic

[11:13:03.542] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:03.543] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-璃月-珉林-东北-9个.json

[11:13:03.957] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.49937198，结果：AmborCostumeWic

[11:13:03.957] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:03.959] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/（恢复）狗粮-璃月-琼玑野.json

[11:13:04.394] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.503868，结果：AmborCostumeWic

[11:13:04.395] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:04.397] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-璃月-琼玑野-绿华池-3个.json

[11:13:04.783] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.521394，结果：AmborCostumeWic

[11:13:04.783] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:04.784] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-璃月-碧水源-盐中之地-3个.json

[11:13:05.177] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.5154877，结果：AmborCostumeWic

[11:13:05.178] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:05.178] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-须弥-道成林-化城郭-西-3个.json

[11:13:05.598] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.5257333，结果：AmborCostumeWic

[11:13:05.598] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:05.599] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-须弥-二净甸-觉王之殿南-6个.json

[11:13:06.029] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.52155095，结果：AmborCostumeWic

[11:13:06.029] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:06.030] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/（恢复）狗粮-须弥-二净甸.json

[11:13:06.467] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.52126473，结果：AmborCostumeWic

[11:13:06.467] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:06.468] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-须弥-失落的苗圃-南-8个.json

[11:13:06.893] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.5360033，结果：AmborCostumeWic

[11:13:06.893] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:06.893] [INF] BetterGenshinImpact.Core.Script.Dependence.Log
assets/狗粮A线@Yang-z/狗粮-须弥-上风蚀地-东北营地-2个.json

[11:13:07.309] [WRN] BetterGenshinImpact.GameTask.Common.TaskControl
无法识别第4位角色，置信度0.53640115，结果：AmborCostumeWic

[11:13:07.309] [ERR] BetterGenshinImpact.GameTask.Common.TaskControl
队伍角色识别失败

[11:13:14.345] [DBG] BetterGenshinImpact.Service.ScriptService
执行脚本时发生异常
Microsoft.ClearScript.ScriptEngineException: Error: A task was canceled.
 ---> Microsoft.ClearScript.ScriptEngineException: Error: A task was canceled.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass105_0`1.<CompletePromise>b__0()
   at InvokeStub_Func`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.ClearScript.Util.InvokeHelpers.InvokeMethodInternal[T](IHostContext context, T method, Object target, Object[] args, Func`4 invoker, Type returnType, ScriptMemberFlags flags)
   at Microsoft.ClearScript.HostItem.InvokeHostMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, CultureInfo culture, Boolean bypassTunneling, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.<>c__DisplayClass151_0.<InvokeReflectMember>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostObject(IntPtr pObject, Boolean asConstructor, Int32 argCount, Ptr pArgs, Ptr pResult)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.<get_InvokeHostObjectFastMethodPtr>g__Thunk|120_0(IntPtr pObject, StdBool asConstructor, Int32 argCount, Ptr pArgs, Ptr pResult)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.V8Object_InvokeMethod(Handle hObject, Ptr pName, Ptr pArgs, Ptr pResult)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.V8Object_InvokeMethod(Handle hObject, Ptr pName, Ptr pArgs, Ptr pResult)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative.V8Object_InvokeMethod(Handle hObject, String name, Object[] args)
   at Microsoft.ClearScript.V8.SplitProxy.V8ObjectImpl.<>c__DisplayClass27_0.<InvokeMethod>b__0(IV8SplitProxyNative instance)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[T](Func`2 func)
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass137_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostAction(IntPtr pAction)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.<get_InvokeHostActionFastMethodPtr>g__Thunk|108_0(IntPtr pAction)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.V8Context_InvokeWithLock(Handle hContext, IntPtr pAction)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Impl_Windows_X64.V8Context_InvokeWithLock(Handle hContext, IntPtr pAction)
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptItem.InvokeMethod(Boolean marshalResult, String name, Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptItem.InvokeMethod(String name, Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptEngine.CompletePromise[T](Task`1 task, Object resolve, Object reject)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass145_1`1.<Microsoft.ClearScript.JavaScript.IJavaScriptEngine.CreatePromiseForTask>b__1(Task`1 _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(Task task, Boolean needsProtection)
   at System.Threading.Tasks.ContinueWithTaskContinuation.Run(Task completedTask, Boolean canInlineContinuationTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at BetterGenshinImpact.Core.Script.Dependence.GlobalMethod.Sleep(Int32 millisecondsTimeout) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Core\Script\Dependence\GlobalMethod.cs:line 16
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass105_0`1.<CompletePromise>b__0()
   at InvokeStub_Func`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.ClearScript.Util.InvokeHelpers.InvokeMethodInternal[T](IHostContext context, T method, Object target, Object[] args, Func`4 invoker, Type returnType, ScriptMemberFlags flags)
   at Microsoft.ClearScript.HostItem.InvokeHostMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.InvokeMember(String name, BindingFlags invokeFlags, Object[] args, Object[] bindArgs, CultureInfo culture, Boolean bypassTunneling, Boolean& isCacheable)
   at Microsoft.ClearScript.HostItem.<>c__DisplayClass151_0.<InvokeReflectMember>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostObject(IntPtr pObject, Boolean asConstructor, Int32 argCount, Ptr pArgs, Ptr pResult)
   --- End of inner exception stack trace ---
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke[T](Func`2 func)
   at Microsoft.ClearScript.ScriptEngine.ScriptInvokeInternal[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass137_0`1.<ScriptInvoke>b__0()
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyManaged.InvokeHostAction(IntPtr pAction)
   --- Script error details follow ---
   Error: A task was canceled.
       at V8ScriptEngine [internal]:1:896 -> Object.defineProperty(this,'EngineInternal',{value:(t=>{let e=t=>t.bind();function r(){return new this(...arguments)}let o=t.isHostObjectKey;delete t.isHostObjectKey;let n=t=>!!t&&!0===t[o],c=Promise,i=JSON,a=Symbol(),s=t.toJson;return delete t.toJson,Object.freeze({commandHolder:{},getCommandResult:e(t=>null==t?t:'function'!=typeof t.hasOwnProperty?'Module'===t[Symbol.toStringTag]?'[module]':'[external]':!0===t[o]?t:'function'!=typeof t.toString?'['+typeof t+']':t.toString()),strictEquals:e((t,e)=>t===e),invokeConstructor:e((t,e)=>{if('function'!=typeof t)throw Error('Function expected');return r.apply(t,Array.from(e))}),invokeMethod:e((t,e,r)=>{if('function'!=typeof e)throw Error('Function expected');return e.apply(t,Array.from(r))}),createPromise:e(function(){return new c(...arguments)}),isPromise:e(t=>t instanceof c),isHostObject:e(n),completePromiseWithResult:e((t,e,r)=>{try{e(t())}catch(o){r(o)}}),completePromise:e((t,e,r)=>{try{t(),e()}catch(o){r(o)}}),throwValue:e(t=>{throw t}),getStackTrace:e(()=>{try{throw Error('[stack trace]')}catch(t){return t.stack}}),toIterator:e(function*(t){try{for(;t.ScriptableMoveNext();)yield t.ScriptableCurrent}finally{t.ScriptableDispose()}}),toAsyncIterator:e(async function*(t){try{for(;await t.ScriptableMoveNextAsync();)yield t.ScriptableCurrent}finally{await t.ScriptableDisposeAsync()}}),getIterator:e(t=>t?.[Symbol.iterator]?.()),getAsyncIterator:e(t=>t?.[Symbol.asyncIterator]?.()),checkpoint:e(()=>{let e=t[a];if(e)throw e}),toJson:e((t,e)=>s?i.parse(s(t,e)):e),parseJson:e(t=>i.parse(t)),asyncGenerator:async function*(){}().constructor})})(this)});
   --- End of inner exception stack trace ---
   at Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.Invoke(Action`1 action)
   at Microsoft.ClearScript.V8.SplitProxy.V8ContextProxyImpl.InvokeWithLock(Action action)
   at Microsoft.ClearScript.V8.V8ScriptEngine.ScriptInvoke[T](Func`1 func)
   at Microsoft.ClearScript.V8.V8ScriptItem.InvokeMethod(Boolean marshalResult, String name, Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptItem.InvokeMethod(String name, Object[] args)
   at Microsoft.ClearScript.V8.V8ScriptEngine.<>c__DisplayClass147_0.<Microsoft.ClearScript.JavaScript.IJavaScriptEngine.CreateTaskForPromise>b__5(Object error)
--- End of stack trace from previous location ---
   at BetterGenshinImpact.Core.Script.Project.ScriptProject.ExecuteAsync(Object context) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Core\Script\Project\ScriptProject.cs:line 77
   at BetterGenshinImpact.Core.Script.Group.ScriptGroupProject.Run() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Core\Script\Group\ScriptGroupProject.cs:line 134
   at BetterGenshinImpact.Service.ScriptService.ExecuteProject(ScriptGroupProject project) in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Service\ScriptService.cs:line 167
   at BetterGenshinImpact.Service.ScriptService.<>c__DisplayClass3_0.<<RunMulti>b__0>d.MoveNext() in D:\HuiPrograming\Projects\CSharp\MiHoYo\BetterGenshinImpact\BetterGenshinImpact\Service\ScriptService.cs:line 82
   --- Script error details follow ---
   Error: A task was canceled.
       at V8ScriptEngine [internal]:1:896 -> Object.defineProperty(this,'EngineInternal',{value:(t=>{let e=t=>t.bind();function r(){return new this(...arguments)}let o=t.isHostObjectKey;delete t.isHostObjectKey;let n=t=>!!t&&!0===t[o],c=Promise,i=JSON,a=Symbol(),s=t.toJson;return delete t.toJson,Object.freeze({commandHolder:{},getCommandResult:e(t=>null==t?t:'function'!=typeof t.hasOwnProperty?'Module'===t[Symbol.toStringTag]?'[module]':'[external]':!0===t[o]?t:'function'!=typeof t.toString?'['+typeof t+']':t.toString()),strictEquals:e((t,e)=>t===e),invokeConstructor:e((t,e)=>{if('function'!=typeof t)throw Error('Function expected');return r.apply(t,Array.from(e))}),invokeMethod:e((t,e,r)=>{if('function'!=typeof e)throw Error('Function expected');return e.apply(t,Array.from(r))}),createPromise:e(function(){return new c(...arguments)}),isPromise:e(t=>t instanceof c),isHostObject:e(n),completePromiseWithResult:e((t,e,r)=>{try{e(t())}catch(o){r(o)}}),completePromise:e((t,e,r)=>{try{t(),e()}catch(o){r(o)}}),throwValue:e(t=>{throw t}),getStackTrace:e(()=>{try{throw Error('[stack trace]')}catch(t){return t.stack}}),toIterator:e(function*(t){try{for(;t.ScriptableMoveNext();)yield t.ScriptableCurrent}finally{t.ScriptableDispose()}}),toAsyncIterator:e(async function*(t){try{for(;await t.ScriptableMoveNextAsync();)yield t.ScriptableCurrent}finally{await t.ScriptableDisposeAsync()}}),getIterator:e(t=>t?.[Symbol.iterator]?.()),getAsyncIterator:e(t=>t?.[Symbol.asyncIterator]?.()),checkpoint:e(()=>{let e=t[a];if(e)throw e}),toJson:e((t,e)=>s?i.parse(s(t,e)):e),parseJson:e(t=>i.parse(t)),asyncGenerator:async function*(){}().constructor})})(this)});

[11:13:14.346] [ERR] BetterGenshinImpact.Service.ScriptService
执行脚本时发生异常: "Error: A task was canceled."

[11:13:14.346] [INF] BetterGenshinImpact.Service.ScriptService
→ 脚本执行结束: "狗粮ABE路线，自动拾取分解", 耗时: 54946 毫秒

[11:13:14.346] [INF] BetterGenshinImpact.Service.ScriptService
------------------------------

[11:13:16.356] [INF] BetterGenshinImpact.Service.ScriptService
脚本 "狗粮ABE路线，自动拾取分解" 状态为禁用，跳过执行

[11:13:16.356] [INF] BetterGenshinImpact.Service.ScriptService
脚本 "自动找凯瑟琳" 状态为禁用，跳过执行

[11:13:16.356] [INF] BetterGenshinImpact.Service.ScriptService
执行被取消

[11:13:16.531] [INF] BetterGenshinImpact.GameTask.TaskRunner
→ "任务结束"
```

- 附件：
在log文件夹中找到的神秘图片一张
![Image](https://github.com/user-attachments/assets/8c577f6b-5aa1-4f47-b021-2132da0af227)

**Comment by huiyadanli** [comment]
![Image](https://github.com/user-attachments/assets/1faae316-2f83-44bd-982e-4f6db66ec3dc)


测试可以，这种识别率低的情况很少见

**Comment by huiyadanli** [comment]
降低了安柏的识别准确度要求
